# Site settings
title: Brian Lubars [blog]
email: blubars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experimental blog using jekyll + github pages.
#baseurl: "/blog/" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: whobars
github_username:  blubars
encoding: UTF-8

# Build settings
markdown: kramdown
collections:
  projects:
    collections_dir: projects
    output: true
